version: '3.8'

services:
  proxycat:
    build: .
    container_name: proxycat
    ports:
      - "1081:1080"  # SOCKS5代理端口
      - "5001:5000"  # Web管理界面端口
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - proxycat_network

networks:
  proxycat_network:
    driver: bridge
